<a href="https://colab.research.google.com/github/ibnudaqiqil/BukuMachineLearning/blob/master/PengenalanNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pengenalan Numpy


##List Python




In [1]:
#Penjumlahan dua List Python
a = [1,2,3]
b = [4,5,6]

print('a+b = ', a+b)


a+b =  [1, 2, 3, 4, 5, 6]


In [2]:
#Perkalian List Python
a = [1,2,3]
print("a x 2 = ", a * 2)

a x 2 =  [1, 2, 3, 1, 2, 3]


In [4]:
#inisialiasi penggunaan Numpy
import numpy as np

In [15]:
#membuat sebuah array 
arr_1_dimensi = np.array([1, 2, 3])
arr_2_dimensi = np.array([[6, 5], [11, 7], [4, 8]])

print("Ukuran Array 1 Dimensi : ", arr_1_dimensi.shape)
print("Ukuran Array 2 Dimensi : ", arr_2_dimensi.shape)


Ukuran Array 1 Dimensi :  (3,)
Ukuran Array 2 Dimensi :  (3, 2)


In [17]:
#membuat array  dengan ukuran 2 x3 berisi 0
c = np.zeros((2, 3))
#membuat array  dengan ukuran 5 x5 berisi 1
d = np.ones((5, 6))

print(c)
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [21]:
c = np.arange(0, 10)
d = np.arange(0, 10, 2)

print(c)
print(d)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [26]:
mean = 10
stdev = 3
jumlah_array = 20
c = np.random.normal(mean, stdev, jumlah_array)
print(c)

[ 7.37278127 11.53170575 12.75691846 11.15975652 11.21522916 10.16939865
  6.55089967 10.56517679 11.58525108  8.36531078 11.23912776  8.90185099
 10.26675212 11.75116488  7.88707855 16.52597278 11.25637802  8.71207888
  5.36175938 17.47303326]


###Indexing Numpy

In [40]:
x = np.arange(10)
#menampilkan semua isi array
print(x)

#menampilkan isi array pertama
print(x[0])

#menampilkan isi array terakhir
print(x[-1])

#menampilkan isi array ke-3 s/d ke-5
print(x[2:5])

#menampilkan isi array dari awal sampai elemen ke-5
print(x[:5])

#menampilkan isi array dari elemen ke-3 sampai terakhir
print(x[2:])

#menampilkan isi array dari elemen ke-3 dari belakang sampai terakhir
print(x[-3:])

#menampilkan element secara terbalik
print(x[::-1])

#menampilkan element secara
print(x[::2])
print(x[::3])

[0 1 2 3 4 5 6 7 8 9]
0
9
[2 3 4]
[0 1 2 3 4]
[2 3 4 5 6 7 8 9]
[7 8 9]
[9 8 7 6 5 4 3 2 1 0]
[0 2 4 6 8]
[0 3 6 9]


In [44]:
x = np.arange(25).reshape(5, 5)
print(x)
print(x[:2, :4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[0 1 2 3]
 [5 6 7 8]]


###Pengolaan Array

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [10]:
#Membuat Numpy array
np_a = np.array([1, 2, 3])
np_b = np.array([4, 5, 6])
print('[Numpy] a+b = ', np_a+np_b)

[Numpy] a+b =  [5 7 9]
